### ISSUE TITLE
Add text return value to DownloadHandlerBuffer reponse

### ISSUE THREAD

**Issue by tomkail** [RageAgainstThePixel/com.utilities.rest#2]
When using the Post functions, DownloadHandlerBuffer is used for the downloadHandler. This results in text not being returned.
I'm not sure if this is by design or not?

**Comment by StephenHodgson** [comment]
Hi @tomkail could you post an example of your code?

**Comment by tomkail** [comment]
Sure! Not much to it really:
`await Rest.PostAsync(query, json, headers);`
It's successful but the response body is null because the PostAsync function uses DownloadHandlerBuffer. On line 629 of Rest.cs you'll see that causes it to return null.

**Comment by StephenHodgson** [comment]
The download handler type is determined by the underlying webrequest 

https://github.com/RageAgainstThePixel/com.utilities.rest/blob/5ffdd06157479d8e99f603b37b0a6081c0eccbd7/Utilities.Rest/Packages/com.utilities.rest/Runtime/Rest.cs#L620

you may need to deserialize and/or reencode the string from the binary data.

**Comment by tomkail** [comment]
Riiight. Makes sense. It's very awkward though! The standard way this type of request is returned is via text, right?

**Comment by StephenHodgson** [comment]
I think it is determined by the returned content type of the response from the server.

**Comment by StephenHodgson** [comment]
If you have control of the server, change your MIME content type to json or text.

```text
application/json
text/plain
```

**Comment by tomkail** [comment]
Hm that might be true, but webRequest.downloadHandler?.text does contain the data I'm expecting, so in this case it feels like the plugin is getting in the way of the way UnityWebRequest is already working.

**Comment by StephenHodgson** [comment]
Ah I see, sure let's add it to the return here

https://github.com/RageAgainstThePixel/com.utilities.rest/blob/5ffdd06157479d8e99f603b37b0a6081c0eccbd7/Utilities.Rest/Packages/com.utilities.rest/Runtime/Rest.cs#L629

```csharp
case DownloadHandlerBuffer _:
    return new Response(true, webRequest.downloadHandler?.text, webRequest.downloadHandler?.data, webRequest.responseCode);
```

Is this what you're suggesting?

**Comment by tomkail** [comment]
Yup!

**Comment by StephenHodgson** [comment]
Give it about 5 min to build, then update to 1.0.2
