### ISSUE TITLE
Download handlers are not properly disposed

### ISSUE THREAD

**Issue by tomkail** [RageAgainstThePixel/com.utilities.rest#4]
This Unity error is thrown when I use this plugin. It appears to be because webrequest upload/download handlers aren't disposed.
The reason for this is apparently because PostAsync calls UnityWebRequest.Post, which creates uploadHandler/downloadHandler. Those handlers are then overwritten but never disposed.

Additionally, you may need to add webRequest.disposeUploadHandlerOnDispose/webRequest.disposeDownloadHandlerOnDispose?

More info on that here: https://forum.unity.com/threads/a-native-collection-has-not-been-disposed-resulting-in-a-memory-leak.1136068/

**Comment by tomkail** [comment]
More info on that here: https://forum.unity.com/threads/a-native-collection-has-not-been-disposed-resulting-in-a-memory-leak.1136068/

**Comment by StephenHodgson** [comment]
Thanks, I'll look into this asap

**Comment by StephenHodgson** [comment]
@tomkail could you also please provide me with the error log stack trace? (mask any sensitive value). It helps.
