### ISSUE TITLE
`DownloadLocation` is not the true location for downloads

### ISSUE THREAD

**Issue by SimonDarksideJ** [RageAgainstThePixel/com.utilities.rest#84]
# Bug Report

## Overview

By default, the Rest utility will download files, however, they are stored in a private "sub folder" (download_cache) and not in the actual download folder.

The correct location is reported by the API when the file is downloaded, but if an app wants to check if the downloaded files exist before downloading them again, it cannot as the `download_cache` is a hidden folder and the files do not exist in the actual downloaded folder.

## To Reproduce
1. Leave the DownloadLocation as the default
2. Download a file
3. Check the folder set by the `DownloadLocation`
4. See no content only a new subfolder which contains the content.

## Expected behavior

If a DownloadLocation is set, the files should be locatable in that folder using the "DownloadLocation" property

**Comment by StephenHodgson** [comment]
I don't understand how this is a problem if using the `Rest.DownloadCacheDirectory`.

**Comment by StephenHodgson** [comment]
I'll update the docs to be explicit about this quirk
