### ISSUE TITLE
CP1252 Encoding error reported on Windows when a new GUID is generated

### ISSUE THREAD

**Issue by SimonDarksideJ** [RageAgainstThePixel/com.utilities.rest#87]
# Bug Report

## Version

Utilities.Rest -> `3.2.3`

## Overview

When using the utility on Windows (although not been able to debug if it happens on other platforms), the following exception is reported in the `DiskDownloadCache` -> `GenerateGuid` method

> System.ArgumentException: 'CP1252' is not a supported encoding name.

## To Reproduce
1. Setup a call to download a Texture using the utility
2. See error reported when the utility tries to cache the texture/call

Unclear if this is all the time or only occasionally (although from the error, I suspect it would happen anytime you try to generate a guide on Windows)

## Expected behavior

Functionality should operate without throwing errors

**Comment by StephenHodgson** [comment]
I haven't ever seen this error, can you elaborate a bit more on the repro setup?

**Comment by SimonDarksideJ** [comment]
Exactly how it sounds unfortunately, Span up a project in test that downloads Textures, Audio, and more.  But when they try to generate a guid to store in the Rest Download cache, an exception is thrown generating the guid.

Seems fine on Android, however it is thrown on Windows

**Comment by StephenHodgson** [comment]
Looking into CP1252, it seems to be an encoding error of a [windows specific code page](https://en.wikipedia.org/wiki/Windows-1252) that is similar to ANSI. 

Might be something to do with the source texture?

**Comment by StephenHodgson** [comment]
Ah I see what the issue might be:

https://github.com/RageAgainstThePixel/com.utilities.rest/blob/99ba36aeacc84314c00413704cdb938016c7cae4/Utilities.Rest/Packages/com.utilities.rest/Runtime/DiskDownloadCache.cs#L25

It is using the "default" encoding of the system, which oddly might be set to the old Windows ANSI encoding? Strange.
I think I can update this to specifically be `UTF-8`

**Comment by SimonDarksideJ** [comment]
Not sure how this line (where the exception occurs) could be affected by the download texture.  But I'll test further.
https://github.com/RageAgainstThePixel/com.utilities.rest/blob/99ba36aeacc84314c00413704cdb938016c7cae4/Utilities.Rest/Packages/com.utilities.rest/Runtime/DiskDownloadCache.cs#L25
